---
title: "Team Project 2" 
author: "Abizer and Luis"
date: "Day 17"
output: 
  github_document:
    pandoc_args: --webtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse=TRUE, prompt=TRUE,comment=NULL,message=FALSE, echo = FALSE, include=TRUE, fig.width = 9, fig.height = 4)
```

```{r packageCheck, include=FALSE}
mypacks <- c("ggplot2","dplyr","readr","tidyr", "ROCR", "boot","class","randomForest","e1071", "stringr","partykit","rpart")  # what packages are needed?
packs <- installed.packages()   # find installed package list
install.me <- mypacks[!(mypacks %in% packs[,"Package"])]  #what needs to be installed?
if (length(install.me) >= 1) install.packages(install.me, repos = "http://cran.us.r-project.org")   # install (if needed)
lapply(mypacks, library, character.only=TRUE)  # load all packages
```

```{r}
key <- read.csv("https://raw.githubusercontent.com/mgelman/data/master/county_facts_dictionary.csv")
```

```{r}
train <- read_csv("https://raw.githubusercontent.com/mgelman/data/master/train.csv")
test <- read_csv("https://raw.githubusercontent.com/mgelman/data/master/test_No_Y.csv")
```


```{r}
train <- train %>% mutate(winner = recode_factor(winner16, Dem = "Democrat", Rep = "Republican"))
```

```{r}

train1 <- train %>% select(RTN130207, INC910213, HSG096213, HSG495213, POP815213, EDU635213, EDU685213, POP715213, AGE295214, AGE775214, PST120214)

xvars <- str_c(names(train1)[1:11], collapse="+")
myform <- as.formula(str_c("winner ~ ", xvars))
myform
```



```{r}
winner.glm <- glm(myform, data = train, family = binomial)

summary(winner.glm)

train <- train %>% mutate(probs = predict(winner.glm, type = "response"),prediction = ifelse(probs >= 0.05,"Republican","Democrat"))

test <- test %>% mutate(probs = predict(winner.glm, newdata = test, type = "response"),prediction = ifelse(probs >= 0.05,"Republican","Democrat"))

train %>% summarize(accuracy = mean(winner == prediction), precision = sum(winner == "Republican" & prediction == "Republican")/sum(prediction == "Republican"), recall = sum(winner == "Republican" & prediction == "Republican")/sum(winner == "Republican"))

ggplot(train,aes(x = probs, color = winner)) + geom_density(size = 1.5) + ggtitle("Forecasted Winner Probabilities ")
```


```{r}
preds_obj1 <- prediction(train$probs, train$winner, label.ordering=c("Democrat","Republican"))
perf_obj1 <- performance(preds_obj1, "tpr","fpr")
perf_df1 <- data_frame(fpr=unlist(perf_obj1@x.values),
                       tpr= unlist(perf_obj1@y.values),
                       threshold=unlist(perf_obj1@alpha.values), 
                       model="train")

ggplot(perf_df1, aes(x=fpr, y=tpr, color=model)) +  geom_line(size=1.5) + 
  labs(x="false positive rate", y="true positive rate", title="ROC curve for logistic regression") + 
  geom_abline(slope=1,intercept=0, linetype=3) 
```


```{r}
set.seed(5)
cost <- function(y, pi) 1-mean(y==(pi>0.05))
train_error <- cv.glm(data = train, winner.glm,cost,5)
train_error$delta[1]
```

# K-nn 

```{r}
set.seed(7)
n <- nrow(train1)

xvars <- str_c(names(train1)[1:11], collapse="+")

train_index <- sample(1:n, size=round(.8*n))

train2 <- train %>% slice(train_index) %>% select( RTN130207, INC910213, HSG096213, HSG495213, POP815213, EDU635213, EDU685213, POP715213, AGE295214, AGE775214, PST120214,winner)

test2 <- test %>% slice(-train_index) %>% select( RTN130207, INC910213, HSG096213, HSG495213, POP815213, EDU635213, EDU685213, POP715213, AGE295214, AGE775214, PST120214)

```

train_knn <- knn(train2[, -1], test2, train2$winner[train_index], k=10)

train4 <- data_frame( y=train2[-train_index],prediction = train_knn) %>% 
  summarize(accuracy = mean(prediction == y), 
                   precision = sum(prediction == "Default" & y == "Default")/sum(prediction == "Default"),
                   recall = sum(prediction == "Default" & y == "Default")/sum(y == "Default"),
                   ) 
```
